### ISSUE TITLE
Other language leads to 404

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1418]
![image](https://user-images.githubusercontent.com/9203229/41723326-cdd11c98-7538-11e8-8bc1-b0e7681ab006.png)

**Comment by mappuji** [comment]
It only happens to RPI, as I try in the x86 version and there is no problem.

`docker-compose.yml`

```yaml
services:
  couchdb:
    expose:
      - 5984
    image: treehouses/couchdb:2.1.1
    ports:
      - "2200:5984"
  db-init:
    image: treehouses/planet-tags:db-init-0.2.1-localization-docker-efd94cd3
    depends_on:
      - couchdb
    environment:
      - COUCHDB_HOST=http://couchdb:5984
  planet:
    image: treehouses/planet-test:0.2.3-master-1c7a9dd9
    ports:
      - "80:80"
    environment:
      - HOST_PROTOCOL=http
      - DB_HOST=127.0.0.1
      - DB_PORT=2200
      - CENTER_ADDRESS=earth.ole.org:2200
    #volumes:
    #  - "./planet/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - couchdb
version: "2"
```


<img width="1280" alt="screen shot 2018-06-21 at 9 19 10 pm" src="https://user-images.githubusercontent.com/11813607/41724943-e3d8b7ca-7598-11e8-862d-762e9e7dcbdf.png">
<img width="1280" alt="screen shot 2018-06-21 at 9 19 16 pm" src="https://user-images.githubusercontent.com/11813607/41724945-e410fd7e-7598-11e8-93d2-61e70f87066b.png">
<img width="1280" alt="screen shot 2018-06-21 at 9 19 20 pm" src="https://user-images.githubusercontent.com/11813607/41724946-e4464ed4-7598-11e8-93e8-170d159bfcf0.png">
