### ISSUE TITLE
create script generate_tags.yml in docker dir

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/planet#1935]
analog to generate_yml.sh we want a script to make tag to do the local conversion for planet and db-init ...

```
services:
  db-init:
    image: treehouses/planet-tags:db-init-0.3.6-update-credentials-6ac0c746
  planet:
    image: treehouses/planet-tags:0.3.6-update-credentials-6ac0c746
version: "2"
```
install-xyz.yml

should generate a `tag.sh` or other script name?
with content of
```
#!/bin/bash

docker tag treehouses/planet-tags:db-init-0.3.6-update-credentials-6ac0c746 treehouses/planet:db-init-local
docker tag treehouses/planet-tags:0.3.6-update-credentials-6ac0c746 treehouses/planet:local
```
